apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uploads
  labels:
    app: uploads
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: xdew-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - xxx
      secretName: uploads-tls
  rules:
    - host: xxx
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uploads
                port:
                  number: 80
