apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: join
  labels:
    app: join
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: xdew-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - xxx
      secretName: join-tls
  rules:
    - host: xxx
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: join
                port:
                  number: 80
