apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home
  labels:
    app: home
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: xdew-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - xxx
      secretName: home-tls
  rules:
    - host: xxx
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home
                port:
                  number: 80
