apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: config-vars
    literals:
      - instances=2

resources:
  - ../../base

replacements:
  - source:
      kind: ConfigMap
      name: config-vars
      fieldPath: data.instances
    targets:
      - select:
          kind: Keycloak
          name: keycloak
        fieldPaths:
          - spec.instances
