apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: config-vars
    literals:
      - host=open.moot.li
      - image=ghcr.io/moot-app/open:0.0.0
      - replicas=1
resources:
  - ../../base
replacements:
  - source:
      kind: ConfigMap
      name: config-vars
      fieldPath: data.host
    targets:
      - select:
          kind: Ingress
          name: open
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: config-vars
      fieldPath: data.image
    targets:
      - select:
          kind: Deployment
          name: open
        fieldPaths:
          - spec.template.spec.containers.0.image
  - source:
      kind: ConfigMap
      name: config-vars
      fieldPath: data.replicas
    targets:
      - select:
          kind: Deployment
          name: open
        fieldPaths:
          - spec.replicas
