apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: legal
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: legal.pikol.app
      - op: replace
        path: /spec/tls/0/hosts/0
        value: legal.pikol.app
  - target:
      kind: Deployment
      name: legal
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
