apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: config-vars
    literals:
      - host=legal.pikol.app
      - replicas=2

resources:
  - ../../base

replacements:
  - source:
      kind: ConfigMap
      name: config-vars
      fieldPath: data.host
    targets:
      - select:
          kind: Ingress
          name: legal
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: config-vars
      fieldPath: data.replicas
    targets:
      - select:
          kind: Deployment
          name: legal
        fieldPaths:
          - spec.replicas
