apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: config-vars
    literals:
      - replicas=1
      - image=ghcr.io/pikol-app/share:0.3.2
      - host=share.pikol.app
resources:
  - ../../base
replacements:
  - source:
      kind: ConfigMap
      name: config-vars
      fieldPath: data.replicas
    targets:
      - select:
          kind: Deployment
          name: share
        fieldPaths:
          - spec.replicas
  - source:
      kind: ConfigMap
      name: config-vars
      fieldPath: data.image
    targets:
      - select:
          kind: Deployment
          name: share
        fieldPaths:
          - spec.template.spec.containers.0.image
  - source:
      kind: ConfigMap
      name: config-vars
      fieldPath: data.host
    targets:
      - select:
          kind: Ingress
          name: share
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
